usernameField = "//input[@id='your_email']"
passwordField = "//input[@id='password']"
loginBtn = "//a[normalize-space()='Login']"
submitBtn = "//input[@name='login']"
okBtn = "//button[normalize-space()='OK']"
succesfullLoginNotif = "(//div[normalize-space()='Welcome Back, Magneto Woman!'])[2]"
logoutBtn = "//a[normalize-space()='Logout']"
loginForm = "//h2[normalize-space()='Login']s"
errorNotifLogin = "//div[@id='swal2-content']"