firstNameField = "//input[@id='firstName']"
lasteNameField = "//input[@id='lastName']"
emailField     = "//input[@id='email']"
phoneNumberField = "//input[@id='phoneNumber']"
addressField   = "//input[@id='address']"
passwordField = "//input[@id='password']"
confirmPasswordField = "//input[@id='confirm_password'] "
registerBtn = "//input[@name='register']"
succesfullRegister = "//button[normalize-space()='OK']"
errorMsgFirstName = "//label[@id='firstName-error']"
errorMsgLastName = "//label[@id='lastName-error']"
errorMsgEmail ="//label[@id='email-error']"
errorMsgPhoneNumber = "//label[@id='phoneNumber-error']"
errorMsgPassword = "//input[@id='password']"
errorMsgConfirmPassword = "//label[@id='confirm_password-error']"
errorMsgPasswordNotMatch = "//label[@id='confirm_password-error']"